name: Docker Pipeline

on:
  push:
    branches:
      - lab_docker
      
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u ${{ secrets.GH_NAME }} -p ${{ secrets.GH_PAT }}
      
      - name: Build Docker image
        run: docker build . --tag ghcr.io/${{ secrets.DOCKER_NAME }}/modprog-project-ghcr:latest
      
      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ secrets.DOCKER_NAME }}/modprog-project-ghcr:latest

      - name: Build Docker image (test)
        run: docker build -t ghcr.io/${{ secrets.DOCKER_NAME }}/modprog-project-test:latest -f Dockerfile.test .

      - name: Push test Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ secrets.DOCKER_NAME }}/modprog-project-test:latest

      - name: Run Docker container
        run: docker run ghcr.io/${{ secrets.DOCKER_NAME }}/modprog-project-ghcr:latest

      - name: Run tests in Docker container
        run: docker run ghcr.io/${{ secrets.DOCKER_NAME }}/modprog-project-test:latest
        